[project]
name = "vizer"
version = "0.1.0"
description = "Data Visualization Application"
requires-python = ">=3.7"
dependencies = [
    "trame>=2.2",
]

[project.optional-dependencies]
dev = [
    "pytest"
]